# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.NET MVC app to Azure Web App - flwins-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore aspnet-get-started.sln

      - name: Build ASP.NET MVC Application
        run: msbuild aspnet-get-started.sln /p:Configuration=Release

      - name: Publish ASP.NET MVC Application
        run: msbuild aspnet-get-started\aspnet-get-started.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishUrl=..\publish\ /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=false

      - name: List published files (for debugging)
        run: |
          echo "Contents of publish directory:"
          if (Test-Path "publish") { Get-ChildItem -Path "publish" -Recurse } else { echo "Publish directory not found" }
          echo "Contents of aspnet-get-started\bin:"
          if (Test-Path "aspnet-get-started\bin") { Get-ChildItem -Path "aspnet-get-started\bin" -Recurse } else { echo "Bin directory not found" }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: aspnet-mvc-app
          path: |
            publish/
            !publish/**/*.pdb

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: aspnet-mvc-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B30DB94BD41E4EEBB360D6EDDCC07DD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DFE5A5F32F414418AFF6A779D62651F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C396785D5194EA99A3ECBBDE88ED6EB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'flwins-dev'
          slot-name: 'Production'
          package: .
          